### ISSUE TITLE
Simplify formatter syntax in yaml

### ISSUE THREAD

**Issue by peterjaap** [elgentos/masquerade#17]
After closing #6 , the syntax has become a little bit unwieldy;

```
creditmemo:
  sales_creditmemo:
    columns:
      customer_note:
        formatter:
          name: sentence
      transaction_id:
        formatter:
          name: randomNumber
          nbDigits: 8
```

A better option would be to also allow this;

```
creditmemo:
  sales_creditmemo:
    columns:
      customer_note:
        formatter: sentence
      transaction_id:
        formatter: randomNumber
```

So we can use the simplified syntax when not passing on any arguments to the formatter.
