### ISSUE TITLE
Give option to give formatter arguments

### ISSUE THREAD

**Issue by peterjaap** [elgentos/masquerade#6]
For example;

`randomNumber($nbDigits = NULL, $strict = false) // 79907610`

We should be able to set `$nbDigits` and `$strict` somehow in our yaml definition.

**Comment by peterjaap** [comment]
Closed by #16

**Comment by peterjaap** [comment]
For example;

```
creditmemo:
  sales_creditmemo:
    columns:
      customer_note:
        formatter:
          name: sentence
      transaction_id:
        formatter:
          name: randomNumber
          nbDigits: 8
```
