### ISSUE TITLE
Configuration ignored or wrong usage on my side

### ISSUE THREAD

**Issue by julienanquetil** [elgentos/masquerade#90]
Hi,

I try to anonymize the customer entity except several domain

So i create a yaml file under

src/config/magento2/customer.yaml

in my yaml file i try first with only one domain to be sure everything is working as expected like

```
customers:
  customer_entity:
    provider: # this sets options specific to the type of table
      where: "`email` not LIKE '%@domaineA.com' "
```

I run my command like that :

`./masquerade.phar run --group=customer --platform=magento2 --config=src/config/magento2/`

but all customer entities are "rewriten" to fake one including the one with domainA.com in the email field.

What I've done wrong ? and is it available to add a multiple filter like we can do on sql 

```
customers:
  customer_entity:
    provider: # this sets options specific to the type of table
      where: "`email` not LIKE '%@domaineA.com' AND `email` not LIKE '%@domaineB.com'"
```

Thanks for your help and thumb up to @peterjaap for the slack help also :)

**Comment by peterjaap** [comment]
@johnorourke might be of help, he wrote the partial anonymization stuff :)

**Comment by julienanquetil** [comment]
To enrich this issue i try to run it not from the Phar one, but from source (like cloning repo / composer install)

I override the default customer yaml file (and reduce scope for testing)


```
customer:
  customer_entity:
    provider: # this sets options specific to the type of table
      where: "`email` not LIKE '%@DOMAINA.fr' AND  `email` not LIKE '%@DOMAINB%'"
    columns:
      email:
        formatter: email
        unique: true
        nullColumnBeforeRun: true
      firstname:
        formatter:
          name: firstName
      lastname:
        formatter: lastName
```

and everything is working as expected. 
So i assuming the phar one didn't read the custom configuration ?

Thanks
